### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/viper#1]
I forked now the repository 'RV'. It should have a more precise name or some acronym.

**Comment by mzechmeister** [comment]
* "corvus" (meaning "crow" or "raven" in Latin) and can be turned into an acronym. (C from Crires, RV, ...?)
* "cervus" (a genus of deer)
* "VIPER"! Velocity and IP EstimatoR

**Comment by chamarthisireesha** [comment]
I have changed it to VIPER

**Comment by mzechmeister** [comment]
;)
