### ISSUE TITLE
inst_OES

### ISSUE THREAD

**Issue by JanaKoehler1985** [mzechmeister/viper#14]
While having again a look at the instrument file I created for  the Ondrejov observatory, I realized that in the fits header of the observation files no RA,DEC positions are given. Therefore berv correction just would be possible with the -targ option. 
Besides I was not able to find out, where I have the cell spectrum from.

Should I/we still offer VIPER for OES data, incuding a warning, that -targ option has to be used or otherwise no berv correction is applied? And I could either upload the cell spectrum here or we say, it is just usable for people having the spectrum themself.

**Comment by mzechmeister** [comment]
I would offer OES. The warning is optional, actually `targ` should be always used.

The cell spectrum should require permission for upload.
The `lib` will grow and grow with all the spectra. (Same for UVES and other inst), while not all files will be needed by single users. I have no solution here, except of auxiliary repositories.

**Comment by JanaKoehler1985** [comment]
Then we may should at least give in the README.md the note, that `targ` always should be used. And maybe also should point out, that it could include errors, when RA,DEC position of the telescope are used instead the real target position. I mean we just have learned that it is not clear to everyone, when they don't know how the berv correction is done in VIPER.
