### ISSUE TITLE
flag names

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/viper#16]
Flagnames should be introduced similar as in
https://github.com/mzechmeister/serval/blob/d94655e9ee559c85cd40859d8f6638e23b2bb0e3/src/read_spec.py#L57-L69

This is more readable and avoids clashes as in:
https://github.com/mzechmeister/viper/blob/4659b72a263111ba8e5b9e63476fd656e9b0dd4b/inst/inst_TLS.py#L45
https://github.com/mzechmeister/viper/blob/4659b72a263111ba8e5b9e63476fd656e9b0dd4b/viper.py#L149
Both uses flag `1`.

It could be defined in `viper.py` or in an auxiliary file, which can be imported by the `inst_.py` files.

**Comment by JanaKoehler1985** [comment]
Just had a look how you did it in serval. I would prefer to do it in viper directly, to avoid to have too much files hanging around- especially as this on would be pretty empty besides of this. Even more, most of these flagging routines are done directly in viper anyhow.
If I would change it now, it would be nice if you wouldn't upload any changes right now, to avoid conflicts.

**Comment by mzechmeister** [comment]
OK, go ahead.

**Comment by JanaKoehler1985** [comment]
As what would you see the clipping due to the chunks? Or should I give it a new number?

**Comment by mzechmeister** [comment]
I don't understand. You can make your bit choice for the flag clip.

**Comment by JanaKoehler1985** [comment]
I know. I am just asking myself as what the clipped values count, which come up by choosing a chunk of the order. 
https://github.com/mzechmeister/viper/blob/96ef9c925861238f5a603a9ba924e8f8e77b8815/viper.py#L152-L155
Should I put it in here: `out=     32, # region outside the template`

**Comment by mzechmeister** [comment]
Ah yes, kappa-sigma clipping (in y direction) and chunk cutting (in x direction) get different flag bits.

**Comment by mzechmeister** [comment]
Flags are now in use:
https://github.com/mzechmeister/viper/blob/feae7ada8b092049f696747431d3fa1659d89c1f/viper.py#L53-L55
