### ISSUE TITLE
Lookpar

### ISSUE THREAD

**Issue by JanaKoehler1985** [mzechmeister/viper#17]
Did some tests yesterday and realized it may would be better for the lookpar to just show relevant pixel range instead of everything.

Could be done by adding `i = i[i_ok]` here
https://github.com/mzechmeister/viper/blob/4953ff9c58ad1ee0b5c8a4dd42d3e502b211ac89/viper.py#L360-L361

Example 1: Using chunks instead of the entire order (-chunks 3 for the following)
Here the entire order is imaged in lookpar. One can see no details about the valid pixel range, as the wavelength solution and the k value becoming large for the outer range. Zooming in doesn't seem to work the right way for these plots.
![grafik](https://user-images.githubusercontent.com/77435060/115506892-b5d14500-a27b-11eb-9b86-93678294a7a9.png)
Using just the relevant (no clipped) values gives you more details and gives you a better image about how stable the parameters are really within one chunk:
![grafik](https://user-images.githubusercontent.com/77435060/115507224-22e4da80-a27c-11eb-8207-64b39c1d55fc.png)

Example 2: Entire order, but clipped values at the edges
Parameters plotted for all values. Here it looks like everything doesn't work out too well at the edges. 
![grafik](https://user-images.githubusercontent.com/77435060/115507619-a56d9a00-a27c-11eb-9d37-94aacd3386d2.png)
Parameters just plotted for the non-clipped values. Shows that it works better that imagined compared to looking at the upper plot.
![grafik](https://user-images.githubusercontent.com/77435060/115507669-b3231f80-a27c-11eb-8b7c-4485448d700b.png)

**Comment by mzechmeister** [comment]
I think, it is better to restrict the plot range in
https://github.com/mzechmeister/viper/blob/4953ff9c58ad1ee0b5c8a4dd42d3e502b211ac89/viper.py#L380

and
https://github.com/mzechmeister/viper/blob/4953ff9c58ad1ee0b5c8a4dd42d3e502b211ac89/viper.py#L382

Something like `gplot(f'[{i0}:f{iend}][0:]',...`.
`i0` is already computed in https://github.com/mzechmeister/viper/blob/4953ff9c58ad1ee0b5c8a4dd42d3e502b211ac89/viper.py#L155.
`i0` could be renamed to `ibeg`. `iend` is yet missing.

**Comment by mzechmeister** [comment]
BTW:
* Cubic degree for 500 px is likely too high.
* The plots show that polynomials are not so good in extrapolating. Other functional forms involving `asin` as in the echelle equation would be more appropriate for the wavelength model. But this is another issue.

**Comment by JanaKoehler1985** [comment]
Get your point.

Have tried out the following and it seems to work:
`gplot(f'[i_ok][0:]', i, Cg, Cp, e_Cp, ...`
whereby i_ok is already defined here:
https://github.com/mzechmeister/viper/blob/4953ff9c58ad1ee0b5c8a4dd42d3e502b211ac89/viper.py#L161
So in my opinion no `iend` would not be needed.

**Comment by JanaKoehler1985** [comment]
-  Agree. Just used it here for testing. Pretty often `degb = 2` really seems to work better.
- I am not happy with the polynomials already for a while, as they didn't seem too fit to well. I also played around with other functions (including `asin`), but nothing was working out that well by now. But it is on my To-Do list.

**Comment by mzechmeister** [comment]
`i_ok` is an array. But the gnuplot range needs at most two values: a start and/or end value.
Also I had a typo: `f'[{i0}:f{iend}]'` => `f'[{i0}:{iend}]'`.

**Comment by JanaKoehler1985** [comment]
Fair enough. My mistake.
Nevertheless, `i0` doesn't work either, as it is for all chunks the same value (the first good one of the entire dataset). 
But the following would do it:
   `ib = (np.where(bp==0)[0][0])` 
   `iend = (np.where(bp==0)[0][-1])`
   `f'[{ib}:{iend}]'`

**Comment by mzechmeister** [comment]
Oh right. I meant chunk begin and end, as used here:
https://github.com/mzechmeister/viper/blob/4953ff9c58ad1ee0b5c8a4dd42d3e502b211ac89/viper.py#L158-L159

Thus:
`ibeg = i0 + chunk*len_ch`
`iend = i0 + (chunk+1)*len_ch`

So it could be defined before https://github.com/mzechmeister/viper/blob/4953ff9c58ad1ee0b5c8a4dd42d3e502b211ac89/viper.py#L153

**Comment by JanaKoehler1985** [comment]
Your definition of `ibeg` and `iend` would work, but not at the position you suggested, as `i0` and `len_ch` are defined just after, or within the `if chunk > 1` function.

How about:
`ibeg = x_ok[0]`
`iend = x_ok[-1]`
just right at the beginning after:
https://github.com/mzechmeister/viper/blob/4953ff9c58ad1ee0b5c8a4dd42d3e502b211ac89/viper.py#L161-L164

**Comment by mzechmeister** [comment]
That's easy and a quick work-around. Yet, it could be smaller than the chunk size.

Also physical coordinate `x` should be plotted (not index values `i`), although both are mostly the same. Thus `xbeg` etc. should be passed.

I'm thinking about:
```python
    i0 = np.where(bp&1==0)[0][0]   # the first pixel that is not trimmed

    xbeg = x[0]
    xend = x[-1]
    if chunks > 1:
        # divide dataset into chunks
        len_ch = int(np.sum(bp&1==0) / chunks)
        ibeg = i0 + chunk*len_ch
        iend = ibeg + len_ch
        bp[:ibeg] |= 32
        bp[iend:] |= 32
        xbeg = x[ibeg]
        xend = x[iend]     
```
It becomes longish.

**Comment by JanaKoehler1985** [comment]
How about:

```python
    i0 = np.where(bp&1==0)[0][0]   # the first pixel that is not trimmed
    len_ch = np.sum(bp&1==0)
    if chunks > 1:
        # divide dataset into chunks
        len_ch = int(len_ch/chunks)
        bp[i0:i0+chunk*len_ch] |= 32
        bp[i0+(chunk+1)*len_ch:] |= 32
    ib = i0 + chunk*len_ch
    iend = i0 + (chunk+1)*len_ch  
```

**Comment by mzechmeister** [comment]
A bit more readable (?):
```python
    ibeg, iend = np.where(bp&1==0)[0][[0,-1]]   # the first and last pixel that is not trimmed
    len_ch = int((iend-ibeg)/chunks)
    ibeg = ibeg + chunk*len_ch
    iend = ibeg + len_ch
    if chunks > 1:
        # divide dataset into chunks
        bp[:ibeg] |= 32
        bp[iend:] |= 32
```

**Comment by JanaKoehler1985** [comment]
Like it! Looks good and works.
In theory one wouldn't even need the `if chunk > 1` anymore. But I guess it is nice to keep it there, so one can see afterwards in the `bp` that data outside the chunks were flagged.
I will uploaded it now.
