### ISSUE TITLE
Right parameter for preclipping?

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/viper#19]
Is the parameter choice in
https://github.com/mzechmeister/viper/blob/c42f743b7ea2d1d46b9eb76c852c46d19066b5bb/viper.py#L310
intended?
Just before a better guess was derived:
https://github.com/mzechmeister/viper/blob/c42f743b7ea2d1d46b9eb76c852c46d19066b5bb/viper.py#L300-L315

**Comment by JanaKoehler1985** [comment]
Indeed it uses here the start guesses of the parameters and is therefor not always a good choice. Maybe it would be better to first run `S_mod.fit`, then do the clipping at the given rms and then run the fitting again. Just as you have implemented it the last time- just without the first kapsig clipping.
