### ISSUE TITLE
interp should be slow

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/viper#20]
The numpy `interp` function is used in
https://github.com/mzechmeister/viper/blob/c42f743b7ea2d1d46b9eb76c852c46d19066b5bb/viper.py#L221

`interp` is finally defined here:
https://github.com/numpy/numpy/blob/c753b23e84a5474c39999fec1f2a6d1ccd54b9a3/numpy/core/src/multiarray/compiled_base.c#L489
and uses binary search in https://github.com/numpy/numpy/blob/c753b23e84a5474c39999fec1f2a6d1ccd54b9a3/numpy/core/src/multiarray/compiled_base.c#L605

However, since the knots are equally spaced, indices can be calculated directly. E.g.
```python
def interp(x, xk, yk):
    s = 1 / (xk[1] - xk[0])   # inverse interval size
    k = (x - xk[0]) * s
    y = yk[k] + (yk[k+1]-yk[k]) * (x-xk[k]) * s
```

Some time testing would be interesting.

**Comment by JanaKoehler1985** [comment]
Well, `np.interp` needed in a simple test in average 2.7e-5 sec, whereby your version took around 3e-5 sec. Seems like `np.interp` is still the faster option. 
Besides, as we talk about 27 microsec running time, I would say it doesn't make sense to speed up the code at that point. Not much to win here.

**Comment by JanaKoehler1985** [comment]
But as you already have put the read in of `w_tpl, f_tpl` out of the `fit_chunk` function, the same could partly be done for `x, w, f, bp, bjd, berv = Spectrum(obsname, o=o, targ=targ)`. In this way time would be saved in case when running the code on chunks > 1.

**Comment by mzechmeister** [comment]
And here is my test
```python
import numpy as np
from scipy.interpolate import interp1d

xk = np.linspace(-10, 10, 1e5)
yk = xk**2
x = 1 * xk[10:-10] + 0.4/1e5   # +some offset form the knots

# linear uniform spline
def lspline(x):
    dxk = xk[1] - xk[0]
    rdxk = 1 / dxk    # reciproke interval size
    k = (x - xk[0]) * rdxk
    k = np.array(k, dtype=int)    # no bound check (no extrapolation)
    y = yk[k] + (yk[k+1]-yk[k]) * (x-xk[k]) * rdxk
    return y

dxk = (xk[1] - xk[0])
rdxk = 1 / dxk    # reciproke interval size
dydx = (yk[1:]-yk[:-1]) * rdxk

#emulate reusing the function and using above precalcuations
def lspline_fast(x):
    k = (x - xk[0]) * rdxk
    k = np.array(k, dtype=int)
    y = yk[k] + dydx[k] * (x-xk[k])
    return y

def lspline_divmod(x):
    k, Dx = divmod(x - xk[0], dxk)
    k = np.array(k, dtype=int)
    y = yk[k] + dydx[k] * Dx
    return y

np.allclose(np.interp(x, xk, yk), lspline(x))
np.allclose(np.interp(x, xk, yk), lspline_fast(x))
np.allclose(np.interp(x, xk, yk), lspline_divmod(x))
np.allclose(np.interp(x, xk, yk), interp1d(xk, yk)(x))

sci1d = interp1d(xk, yk)

%timeit np.interp(x, xk, yk)
%timeit lspline(x)
%timeit lspline_fast(x)
%timeit sci1d(x)
%timeit lspline_divmod(x)
 ```

Timing yields
```
np:           556 µs ± 18.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
lspline:      1.11 ms ± 2.41 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
lspline_fast: 932 µs ± 1.32 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
scipy:        619 µs ± 5.19 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
divmod:       4.19 ms ± 13 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Conclusion: Probably still too much temporary arrays (~9) created in `lspline_fast`. So `np.interp` is fastest despite
binary search. (I would like to the improvement with `numba`, but it needs to be installed).
Thus, we can stick to `np.interp`.
