### ISSUE TITLE
Variable renaming

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/viper#27]
Current names are often to short and should be more verbose.
Agreed is in **bold**. Please edit this description.

current Name | proposals |  example location/comments
--|--|--
n | ~~num_obs~~ <br> **n** | https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/viper.py#L806 num_obs sounds like (total) number of observations.<br>for a running integer index, the name n should be ok.
o | ~~num_order~~ <br> o <br> **order** |  https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/viper.py#L786
a | **par_norm** |  https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/viper.py#L325
b | **par_wave** <br> par_disp | disp = dispersion
c | ~~par_add~~ <br> **par_bkg** <br> par_bg  <br> par_backgr |  
s | **par_ip** |  
t | par_tell <br> **par_atm** |  
v | **par_rv** |  
p | ~~par_all~~ <br>**params** | preserve subscript par for parameter subsets.
pg | ~~par_guess~~ <br> **params_guess** |  
x | **pixel** <br> pix <br> x |  
w | **wave_obs** <br> wave_data |
w_tpl | **wave_tpl** |
w_I2 | **wave_cell** |
f | ~~data_obs~~ <br> **spec_obs** <br> flux_obs <br> flux_data |  
f_I2 | ~~data_cell~~ <br> **spec_cell** |
f_tpl | ~~data_tpl~~  <br> **spec_tpl** |
e | ~~data_err~~ <br> e_spec <br> ~~**e_obs**~~ <br> unc_obs  <br> e_spec_obs <br> err_obs |  unc = uncertainty
bp | ~~badpixel~~ <br> **flag_pixel** <br> flagmap |  
uj | log_wave_cell <br> lnwave_cell  <br> ~~wave_cell_log~~  <br> ~~wave_cell_ln~~|https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/viper.py#L248-L250 maybe log is easier to understand then ln (even if ln is used)? <br>MZ: I was aware of this "readability" argument. I chose `ln` in first place, because in math mode (latex) `ln` is clearly naturalis, while `log` can be `ln` or `log10`. For me `ln, log = np.log, np.log10` , thus the names `log` would be wrong.
ui | ??? <br> lnwave_obs |  https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/model.py#L195
iod_j | log_data_cell  <br> wave_spec_log |  
s | slice_cell  <br> wave_range_cell |  
s_s | slice_tpl  <br> wave_range_tpl |  
sj | slice_log_cell |  
  |   |  
dega | **deg_norm** |  
degb | **deg_wave** |  
degc | ~~deg_add~~ <br> **deg_bgk** <br> deg_bg <br> deg_backgr |  
degar | deg_norm_rat <br> deg_norm_pade <br> deg_norm_denominator | "Rational polynomial degree of denominator for flux normalisation." https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/viper.py#L236-L238 Alternatively, this parameter might be merged with dega: <br>`deg_norm <num>` (polynomial) <br>`deg_norm <num> <num>` (Pade/rational polynomial)<br>`deg_norm <num> 1` (normal polynomial but evaluate through Pade function)<br>Convinient on command line. Unpacking needed in code.
vg | **rv_guess** |

**Comment by mzechmeister** [comment]
Generally, I prefer the quantity to be first and the subscript/label afterwards, i.e. `flux_obs` instead of `obs_flux`.
On the other hand the presence of many prefixes/suffixes like `par` or `data` may indicate that container/classes should be used. Then the quatities would become attributes (looking like suffixes), `par.rv` or `obs.wave`.

Please include the issue number in commits.

**Comment by JanaKoehler1985** [comment]
Somehow your last changes were removed after I added my last changes :-/ Sorry!

`par_extra` also is not really clear. What is actually the idea behind this parameter? I never totally understood this.

**Comment by mzechmeister** [comment]
I used the parameter `c` for CES data to allow for an additive background in the observation (e.g. incomplete bias/scattered light subtraction). Then I found it more performed, i.e. even lower residuals, when applied to the iod spectrum. A bit unexpected; but FTS spectra may also have similar problems. Well, that is where the parameter currently lives 
https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/model.py#L93
You may try it for fun.

**Comment by JanaKoehler1985** [comment]
Thanks! I found it in the program and also realized the results are better when using it, but I never totally understood its meaning. Now it makes more sense!
I think than something like deg_bkg really makes sense. Nevertheless, I never used bkg as abbreviation for background. Maybe deg_bg or deg_backgr? Otherwise deg_bkg also is fine with me.

**Comment by mzechmeister** [comment]
bkg: I have seen it several time, also in eso pipelines https://ftp.eso.org/pub/dfs/pipelines/uves/uves-fibre-pipeline-manual-6.1.6.pdf

**Comment by JanaKoehler1985** [comment]
`    i_ok = np.where(bp==0)[0]`
`    x_ok = x[i_ok]`

If I get it right, i_ok and x_ok are just the same. Even more i and x are the same:
`    i = np.arange(f.size)`
`    x = np.arange(f.size) `
Is there any reason to keep both?

**Comment by JanaKoehler1985** [comment]
https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/viper.py#L303
https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/model.py#L93

Even if we allow the user to choose degc, we always just allow degc=1 in the code. So may we should remove degc or allow it in the code.

**Comment by mzechmeister** [comment]
`x` = pixel number/coordinate, `i` = data/pixel index. That was the idea.
Often they are them assuming `x` starts with zero. But when chunking first `x`can be larger than zero.

`degc` is used in the next line:
https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/viper.py#L304

**Comment by mzechmeister** [comment]
I can't see, where  `i` is used :thinking:. So may the line can be deleted.
But the idea still holds with names `i_ok`, `iend` etc.

**Comment by JanaKoehler1985** [comment]
I see. Well, i is used in the lookpar option and in the calculation of the individual parameters. Starting from line 621 on.

**Comment by JanaKoehler1985** [comment]
> degc is used in the next line

It is. But there we just differ between degc = 0 and not 0. And in model.py we also just use the first value:
https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/model.py#L93

**Comment by mzechmeister** [comment]
It shows how more extra parameters than just one could be passed.
Maybe there are better ways.
Also polynomials for bgk are probably not or rarely need.
Anyway, I would keep and only rename it.

**Comment by mzechmeister** [comment]
When discussing `ui` and `uj`, I realise now that the subscripts `i` and `j` may vanish. That would be a pity.
`i` indicated sampling in data space, while `j` was the supersampling in model space. 
`i` and `j` were easy to recognise, at least for me, and prevents mixing the both spaces.
The conversion between both happens in
https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/model.py#L107

`i` is basically synonym for `obs` (data sampling). While `i` was often suppressed (e.g. just `f` instead of `fi` or `f_i`), while `obs` is not suppressed anymore (`spec_obs`). Thus it becomes more verbose (readable?).

Originally, I thought `u` would be a good single-char variable name, but I can live with `lnwave`.

**Comment by mzechmeister** [comment]
Instead of `wave` and `w`, another possibility would be to use `λ`.
```
λ = 550
lnλ = np.log(λ)
```
Also readable, albeit again a single-char variable name.
This is unicode, which I think, is fully supported by Python 2(?) and 3. But some (old?) editors may screw it up?

One reason, for me to use single-char names, was that the names can be directly associated with equations from a potential paper
```math
\chi^2 = \sum_i S_i - S_v(x_i) 
```
```math
S_v(x) = {\rm IP}(x,\lambda) \otimes [s_{\star,v}(\lambda)\cdot t(\lambda)]
```
Seems like a conflict between coding and scientific notation.

**Comment by JanaKoehler1985** [comment]
Even so, I am mainly done now with most of the changes, I haven't touched `ui` and `uj` by now. Nor I have `i`. While it may would be a possibility to leave `ui` and `uj` , `i` defintely cannot stay like this. But I also don't know how to name it best either.

> Thus it becomes more verbose (readable?).

Well I guess it depends on the definition of readable. As we are used to the current version of the code and know all the variables by heart and may have the related formula in mind, I would say it is not readable for people who look at the code for the first time. I also have to admit it took me a while to understand the meaning of all variables- and the names were not helpful in this regard. Furthermore, more detailed names make it easier to search for variables in the code. F.e. if I search for `f` it will find it everywhere also in other variable names and comments (that's what made these changes so hard). But if I search for `spec_obs`, it will just find and mark what I am looking for.

**Comment by JanaKoehler1985** [comment]
I wouldn't start with additional characters in the code. And in my opinion ` λ` is one. I wouldn't be surprised if this would cause troubles at some point.

**Comment by mzechmeister** [comment]
When reading the code, I find now the term `spec` less optimal. It does not exactly capture the physical quantity. I think, `spec`/spectrum (spectral) should be preserved for the set wavelength+flux (#28). Thus, `flux` should be preferred. However, this is only a good choice for the star; but not for spectra of absorbing gases, where it is "transmittance" (too long as variable name).  `spec` captures somehow both, thus I guess we chose it in first place.

I'm just thinking loud and going in cycles.

**Comment by JanaKoehler1985** [comment]
Well, several paper also using flux when plotting cell or telluric spectra. Would be fine with me. 
Plus, I would prefer a name that works for all kind of spectra.
