### ISSUE TITLE
expose molec as command line argument

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/viper#30]
Currently,
https://github.com/mzechmeister/viper/blob/41cdd82c96e09124984b7466f396d74404bf18e6/viper.py#L690-L700

What I have in mind
```python
argopt('-molec', help='molecular specifies (just for CRIRES+)', default=None, 
     choices=['H2O', 'CH4', 'N2O', 'CO2', 'CO'],
     const=Inst.molec)
...
if molec:
   ...
   for mol in molec:
      ...

```

**Comment by JanaKoehler1985** [comment]
The molecule selection for the user is one of the things on my TO-DO list. I just wanted to finish the variable renaming first and than to it as separated commit.
But I would offer it not just for CRIRES+ and I also would give an option `all`.
