### ISSUE TITLE
gui for vpr

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/viper#33]
It would be nice to have a gui to analyse the RV posteriori.
Currently, this is done by from command line with `vpr.py`.

The gui (`vpr_gui.py` or a tab in `GUI_viper.py`) should allow to select the orders/chunks (e.g. checkboxes; needs to be created dynamically).
It can call `vpr.py` to get statistics (rms) and plots.

**Comment by JanaKoehler1985** [comment]
Not a bad idea. If a GUI like the current one for viper is good enough it shouldn't be too complicated as I can use it as a template. From there vpr.py can be started just like it is done now for viper.

**Comment by JanaKoehler1985** [comment]
I am basically done with it. But one last question, is `nset` meant to just work for plotting the residuals, but not for plotting the RVs?

**Comment by mzechmeister** [comment]
I wasn't aware that there is a `res` and `nset` option!
If running, it seems even nice.
`vpr test -nset :4 -res -oset [7,8,10]` failed with `TypeError: object of type 'slice' has no len()`;
but `vpr test -nset 0,1,2,3 -res -oset [7,8,10]` works.

So, indeed `nset` is currently implemented only for the `res` option. So you can ignore it for now.
It would be nice, if `nset` would be fully functional. But this is another issue.

**Comment by JanaKoehler1985** [comment]
Well, for`res` you even have to select `nset`. But in the moment it work just if you enter a single `int` value.

I have now uploaded a possible first version. Nevertheless, I have not used vpr.py that much by now and I am not sure I know and understand all options to full extend. So if you are missing something, or you had something else in mind, let me know.

**Comment by mzechmeister** [comment]
FYI, I just found there are also "automatic" wrappers:
https://github.com/chriskiehl/Gooey
