### ISSUE TITLE
License header

### ISSUE THREAD

**Issue by JanaKoehler1985** [mzechmeister/viper#37]
I would like to add a license header to our files, based on GPL v3 it would be:

 viper
 Copyright (C) Mathias Zechmeister and Jana Koehler

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along
 with this program; if not, write to the Free Software Foundation, Inc.,
 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

**Comment by mzechmeister** [comment]
Ok. (I have no clue about those stuff.)

**Comment by JanaKoehler1985** [comment]
(Me neither.) 
I will add it later.

**Comment by mzechmeister** [comment]
Closed with f272d98ca3bd26fdb29c8fc30b8f3532e874529c.
