### ISSUE TITLE
viper GUI

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/viper#46]
Ideas/feature requests for viper GUI
- [x] little help/popup icons which provides the help strings of the command line option.
- [x] checkboxes molecules
- [x] group gui: star, cell, tellurics

**Comment by JanaKoehler1985** [comment]
Coming next:
- [x]  search button flagfile
- [x]  checkboxes molecules
- [x]  extended nset, oset entry
- [x]  entry for look, lookfast
- [x]  print console command
- [x]  read in FTS Cell -> remove ocen
- [ ]  popup help icons

I am also planning to update the Layout of the GUI_vpr.py using the same way as I used now to create GUI_viper.py.

**Comment by JanaKoehler1985** [comment]
What do you mean by "group gui: star, cell, tellurics" ?

**Comment by mzechmeister** [comment]
In viper, options are sorted alphanumerically. I guess this is ok.
For the GUI they should be arranged conceptually.  It arised during a discussion with Evangelos.

So maybe something like  this:
* data
  - files
  - nset
  - oset
  - chunks
* star
  - tpl ...
  - rv_guess
  - [ ] create tpl
* cell
  - [ ] nocell
* telluric
  - mask/add
  - molecules
  - [ ] fit abundance
  - [ ] fit rv
* model
  - IP
  - norm
  - wave
* statistics others
  - kapsig
  - weight errors


You may consider Tkinter LabelFrame.

**Comment by JanaKoehler1985** [comment]
I am open for discussions to re-order things and I am aware not everything is perfect yet. But I am not sure if I like your way of suggested structure. I would prefer it to have the read in of all files together, as well as having all options together. This makes more sense to me.

(Could't have Evangelos came up with this discussion last week as I was visiting you? Would have been much easier to discuss this in person.)

**Comment by JanaKoehler1985** [comment]
How about leaving all read in files together, like it is right now, but sort/group the parameters similar to your suggestion? Would that be a compromise?

**Comment by JanaKoehler1985** [comment]
I was thinking about order the parameters using (partly) your suggestion and did some tests- see cut-out picture below. Is this what you had in mind? 
Of cause it is not complete and just should give an idea about how it could look like. But I would like to clarify before changing everything and than may ending up changing it again, if you would prefer it another way.

![Bildschirmfoto vom 2023-03-15 15-10-50](https://user-images.githubusercontent.com/77435060/225335138-7e21fa82-4480-4e63-895f-9bb3c5391cbd.png)

**Comment by mzechmeister** [comment]
Yes, that is what I meant.

Some more comments:
- `Statistics` after Tellurics
- `Statistics` ~> `Fit parameters` (captures also `vcut`, which is not a statistics parameter)
- molecule checkboxes inside Tellurics
- generally, I like more it, if buttons/input fields goes vertical direction, as here

![image](https://user-images.githubusercontent.com/32583239/225344399-9dbcb9c7-b2d1-4d03-85e5-f2da88b687b0.png)
or as in the old vpr GUI
![image](https://user-images.githubusercontent.com/32583239/225345654-83e6e95e-a97f-4108-ac83-61f1e740fa62.png)

**Comment by JanaKoehler1985** [comment]
About point 1 and 3: That was the plan ;-) But as said... this was just a little demo test.

Where would you put vcut?

I also prefer the vertical direction. Nevertheless, it is not enough space to put everything in vertical direction. But I could (try to) put two boxes next to each other in horizontal direction and than use the vertical inside the box.

**Comment by mzechmeister** [comment]
`vcut`:  to `Fit parameters` or maybe to `data` next to `chunks`.
 `Fit parameters` ->  `Fit setup`?

**Comment by JanaKoehler1985** [comment]
Ok. Nevertheless, can we, as already asked above, agree to keep the reading in of the data and the parameters separated as it is in the current version? I would prefer it this way.

**Comment by mzechmeister** [comment]
I guess, with "data" you mean also template, cell, and telluric files.
Currently, the four search fields at top looks nicely aligned.
![image](https://user-images.githubusercontent.com/32583239/225355761-405b9d22-a545-40d5-be2f-b1bc41554979.png)
But I'm not tied to this. I prefer conceptional grouping.
Indeed, tpl and cell files are just model components stored as tables, but they are not data (anymore).
Also e.g. `tpl file` and `create tpl` should go together and one might expect more parameters.

**Comment by JanaKoehler1985** [comment]
> I guess, with "data" you mean also template, cell, and telluric files.

Exactly! 

> Currently, the four search fields at top looks nicely aligned.

I also like it how these fields are nicely aligned at the moment. And I would prefer to keep it like that. Furthermore, in this way it is also easier to create a layout for the rest of the parameters- especially if we prefer vertical direction for parameter inputs.

**Comment by mzechmeister** [comment]
Well, then go ahead and let's see how it looks.

**Comment by JanaKoehler1985** [comment]
I will try to build something that looks the following way. Labelframe names not shown here, but would be: data, template, model, fit parameters, telluric

![Bildschirmfoto vom 2023-03-16 14-34-35](https://user-images.githubusercontent.com/77435060/225634083-bfcf876d-4cb7-4622-bd51-e17002ae3778.png)

**Comment by mzechmeister** [comment]
Yeah, the GUI looks nice.
