### ISSUE TITLE
issue with parameters in lambda func ?

### ISSUE THREAD

**Issue by chamarthisireesha** [mzechmeister/viper#8]
https://github.com/chamarthisireesha/VIPER/blob/755379fdec749faf2a6d6217eaf89233bad394db/viper.py#L188-L190

The parameters are 3 sets [v,a,b] but the function calls a combination of 4 ?

**Comment by chamarthisireesha** [comment]
reference In [91] of https://github.com/chamarthisireesha/VIPER/blob/master/viper_jupyter.ipynb

**Comment by mzechmeister** [comment]
In `[69]` `a` is replaced by an np.array (while previously it was a list with one scalar):
```a, e_a = curve_fit(S_a, i[i_ok], f[i_ok])```
This leads to:
```
----> 3 p, e_p = curve_fit(S_g, i[i_ok], f[i_ok], p0=[v]+a+[0]*3+[*bg]+s[0:1], epsfcn=1e-12)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 
```
In this case `a+[0]*3` should be replaced by `[*a]`. (However, this might break other cases.)

**Comment by mzechmeister** [comment]
This should be fixed in https://github.com/chamarthisireesha/VIPER/commit/01a2091e441f9fecc881adc8749aa58138629047#r40212396
