### ISSUE TITLE
IP as super Gaussian

### ISSUE THREAD

**Issue by chamarthisireesha** [mzechmeister/viper#9]
`python viper.py "data/TLS/hd189733/*" data/TLS/Deconv/HARPS*fits -oset 19:21 -nset :4 -lookpar -ip 'sg'`

the fit fails to converge in this scenario.  RuntimeWarning: divide by zero encountered in power
  IP_k = np.exp(-abs(vk/s)**e)   # Gauss IP

**Comment by mzechmeister** [comment]
This works for me. Do you still have the problem?
